// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SastImg.Infrastructure.Persistence;

#nullable disable

namespace SastImg.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SastImgDbContext))]
    partial class SastImgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SastImg.Domain.AlbumEntity.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("_accessibility")
                        .HasColumnType("integer")
                        .HasColumnName("accessibility");

                    b.Property<long>("_authorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("_categoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<List<long>>("_collaborators")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("bigint[]")
                        .HasColumnName("collaborators");

                    b.Property<DateTime>("_createdAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("_isRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("_updatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("_categoryId")
                        .HasDatabaseName("ix_albums_category_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("SastImg.Domain.CategoryEntity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("_name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories__name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SastImg.Domain.TagEntity.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("_name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags__name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SastImg.Domain.AlbumEntity.Album", b =>
                {
                    b.HasOne("SastImg.Domain.CategoryEntity.Category", null)
                        .WithMany()
                        .HasForeignKey("_categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_categories_category_id");

                    b.OwnsOne("SastImg.Domain.AlbumEntity.Cover", "_cover", b1 =>
                        {
                            b1.Property<long>("AlbumId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<bool>("IsLatestImage")
                                .HasColumnType("boolean")
                                .HasColumnName("cover_is_latest_image");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("cover_url");

                            b1.HasKey("AlbumId");

                            b1.ToTable("albums");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId")
                                .HasConstraintName("fk_albums_albums_id");
                        });

                    b.OwnsMany("SastImg.Domain.AlbumEntity.Image", "_images", b1 =>
                        {
                            b1.Property<long>("album_id")
                                .HasColumnType("bigint")
                                .HasColumnName("album_id");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("_description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<bool>("_isRemoved")
                                .HasColumnType("boolean")
                                .HasColumnName("is_removed");

                            b1.Property<int>("_likes")
                                .HasColumnType("integer")
                                .HasColumnName("likes");

                            b1.Property<List<long>>("_tags")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(false)
                                .HasColumnType("bigint[]")
                                .HasColumnName("tags");

                            b1.Property<string>("_title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title");

                            b1.Property<DateTime>("_uploadtedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<string>("_url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.Property<int>("_views")
                                .HasColumnType("integer")
                                .HasColumnName("views");

                            b1.HasKey("album_id", "Id")
                                .HasName("pk_images");

                            b1.ToTable("images", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album_id")
                                .HasConstraintName("fk_images_albums_album_id");
                        });

                    b.Navigation("_cover");

                    b.Navigation("_images");
                });
#pragma warning restore 612, 618
        }
    }
}
