// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SNS.Infrastructure.Persistence;

#nullable disable

namespace SNS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SNSDbContext))]
    [Migration("20240412194922_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SNS.Domain.Bookmarks.Bookmark", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user");

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("image");

                    b.HasKey("UserId", "ImageId")
                        .HasName("pk_bookmarks");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("SNS.Domain.Follows.Follow", b =>
                {
                    b.Property<long>("Follower")
                        .HasColumnType("bigint")
                        .HasColumnName("follower");

                    b.Property<long>("Following")
                        .HasColumnType("bigint")
                        .HasColumnName("following");

                    b.HasKey("Follower", "Following")
                        .HasName("pk_follows");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("SNS.Domain.Likes.Like", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user");

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("image");

                    b.HasKey("UserId", "ImageId")
                        .HasName("pk_likes");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("SNS.Domain.Subscribes.Subscribe", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user");

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album");

                    b.HasKey("UserId", "AlbumId")
                        .HasName("pk_subscribes");

                    b.ToTable("subscribes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
