// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Square.Infrastructure.Persistence;

#nullable disable

namespace Square.Infrastructure.Persistence.QueryMigrations
{
    [DbContext(typeof(SquareDbContext))]
    [Migration("20240401060556_QueryFix1")]
    partial class QueryFix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("query")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Square.Application.ColumnServices.Models.ColumnModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_columns");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_columns_topic_id");

                    b.ToTable("columns", "query");
                });

            modelBuilder.Entity("Square.Application.TopicServices.TopicModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.ToTable("topics", "query");
                });

            modelBuilder.Entity("Square.Application.ColumnServices.Models.ColumnModel", b =>
                {
                    b.HasOne("Square.Application.TopicServices.TopicModel", null)
                        .WithMany("ColumnModels")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_columns_topics_topic_id");

                    b.OwnsMany("Square.Domain.ColumnAggregate.ColumnEntity.ColumnLike", "Likes", b1 =>
                        {
                            b1.Property<long>("ColumnId")
                                .HasColumnType("bigint")
                                .HasColumnName("column_id");

                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            b1.HasKey("ColumnId", "UserId")
                                .HasName("pk_column_likes");

                            b1.ToTable("column_likes", "query");

                            b1.WithOwner()
                                .HasForeignKey("ColumnId")
                                .HasConstraintName("fk_column_likes_columns_column_id");
                        });

                    b.OwnsMany("Square.Application.ColumnServices.Models.ColumnImage", "Images", b1 =>
                        {
                            b1.Property<long>("id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("ThumbnailUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("thumbnail_url");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("id")
                                .HasName("pk_column_images");

                            b1.ToTable("column_images", "query");

                            b1.WithOwner()
                                .HasForeignKey("id")
                                .HasConstraintName("fk_column_images_columns_id");
                        });

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Square.Application.TopicServices.TopicModel", b =>
                {
                    b.OwnsMany("Square.Domain.TopicAggregate.TopicEntity.TopicSubscribe", "Subscribes", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            b1.Property<long>("TopicId")
                                .HasColumnType("bigint")
                                .HasColumnName("topic_id");

                            b1.HasKey("UserId", "TopicId")
                                .HasName("pk_topic_subscribes");

                            b1.HasIndex("TopicId")
                                .HasDatabaseName("ix_topic_subscribes_topic_id");

                            b1.ToTable("topic_subscribes", "query");

                            b1.WithOwner()
                                .HasForeignKey("TopicId")
                                .HasConstraintName("fk_topic_subscribes_topics_topic_id");
                        });

                    b.Navigation("Subscribes");
                });

            modelBuilder.Entity("Square.Application.TopicServices.TopicModel", b =>
                {
                    b.Navigation("ColumnModels");
                });
#pragma warning restore 612, 618
        }
    }
}
